create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  account_number text not null unique,
  krw_balance numeric(20, 2) not null default 0 check (krw_balance >= 0),
  usd_balance numeric(20, 4) not null default 0 check (usd_balance >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.accounts is '모의투자 계좌 기본정보와 통화별 예수금';

insert into public.accounts (id, account_number, krw_balance, usd_balance)
values (1, 'POSCO-000001', 10000000, 0)
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.accounts', 'id'),
  coalesce((select max(id) from public.accounts), 1),
  true
);

alter table public.accounts enable row level security;

-- 현재 단계에서는 service_role을 사용하는 Express 서버만 접근합니다.
-- Supabase Auth를 연결할 때 user_id 컬럼과 사용자별 RLS 정책을 추가합니다.
