create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  symbol text not null check (length(trim(symbol)) > 0),
  created_at timestamptz not null default now(),
  unique (account_id, symbol)
);

create index if not exists favorites_account_id_idx
  on public.favorites (account_id);

comment on table public.favorites is '모의계좌별 관심 종목';

alter table public.favorites enable row level security;

-- 현재 단계에서는 서버의 Secret/service_role 키로만 접근합니다.
-- Supabase Auth 도입 시 계좌 소유자를 확인하는 사용자별 RLS 정책을 추가합니다.
