create table if not exists public.holdings (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  symbol text not null check (length(trim(symbol)) > 0),
  category text not null check (category in ('stocks', 'bonds', 'crypto')),
  quantity numeric(30, 8) not null check (quantity > 0),
  avg_price numeric(30, 8) not null check (avg_price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (account_id, symbol)
);

create index if not exists holdings_account_id_idx on public.holdings (account_id);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  account_id bigint not null references public.accounts(id) on delete cascade,
  symbol text not null check (length(trim(symbol)) > 0),
  category text not null check (category in ('stocks', 'bonds', 'crypto')),
  side text not null check (side in ('BUY', 'SELL')),
  order_type text not null default 'MARKET' check (order_type in ('MARKET', 'LIMIT')),
  quantity numeric(30, 8) not null check (quantity > 0),
  requested_price numeric(30, 8),
  execution_price numeric(30, 8) not null check (execution_price > 0),
  total_amount numeric(30, 2) not null check (total_amount >= 0),
  status text not null default 'FILLED' check (status in ('FILLED', 'REJECTED', 'CANCELLED')),
  created_at timestamptz not null default now()
);

create index if not exists orders_account_created_idx on public.orders (account_id, created_at desc);

alter table public.holdings enable row level security;
alter table public.orders enable row level security;

create or replace function public.place_spot_order(
  p_account_id bigint, p_symbol text, p_category text, p_side text,
  p_order_type text, p_quantity numeric, p_requested_price numeric,
  p_execution_price numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_account public.accounts%rowtype;
  v_holding public.holdings%rowtype;
  v_order public.orders%rowtype;
  v_total numeric(30, 2);
  v_new_quantity numeric(30, 8);
  v_new_avg_price numeric(30, 8);
begin
  if p_category not in ('stocks', 'bonds', 'crypto') then
    raise exception using errcode = '22023', message = '지원하지 않는 상품군입니다.';
  end if;
  if p_side not in ('BUY', 'SELL') then
    raise exception using errcode = '22023', message = '지원하지 않는 주문 방향입니다.';
  end if;
  if p_order_type not in ('MARKET', 'LIMIT') then
    raise exception using errcode = '22023', message = '지원하지 않는 주문 유형입니다.';
  end if;
  if p_quantity is null or p_quantity <= 0 or p_execution_price is null or p_execution_price <= 0 then
    raise exception using errcode = '22023', message = '수량과 체결가는 0보다 커야 합니다.';
  end if;

  select * into v_account from public.accounts where id = p_account_id for update;
  if not found then
    raise exception using errcode = 'P0002', message = '계좌를 찾을 수 없습니다.';
  end if;

  v_total := round(p_quantity * p_execution_price, 2);
  select * into v_holding from public.holdings
  where account_id = p_account_id and symbol = p_symbol for update;

  if p_side = 'BUY' then
    if v_account.krw_balance < v_total then
      raise exception using errcode = 'P0001', message = '잔고가 부족합니다.';
    end if;
    update public.accounts set krw_balance = krw_balance - v_total, updated_at = now()
    where id = p_account_id returning * into v_account;
    if v_holding.id is null then
      insert into public.holdings (account_id, symbol, category, quantity, avg_price)
      values (p_account_id, p_symbol, p_category, p_quantity, p_execution_price)
      returning * into v_holding;
    else
      v_new_quantity := v_holding.quantity + p_quantity;
      v_new_avg_price := ((v_holding.avg_price * v_holding.quantity) + (p_execution_price * p_quantity)) / v_new_quantity;
      update public.holdings set quantity = v_new_quantity, avg_price = v_new_avg_price,
        category = p_category, updated_at = now()
      where id = v_holding.id returning * into v_holding;
    end if;
  else
    if v_holding.id is null or v_holding.quantity < p_quantity then
      raise exception using errcode = 'P0001', message = '보유수량이 부족합니다.';
    end if;
    update public.accounts set krw_balance = krw_balance + v_total, updated_at = now()
    where id = p_account_id returning * into v_account;
    v_new_quantity := v_holding.quantity - p_quantity;
    if v_new_quantity = 0 then
      delete from public.holdings where id = v_holding.id;
      v_holding := null;
    else
      update public.holdings set quantity = v_new_quantity, updated_at = now()
      where id = v_holding.id returning * into v_holding;
    end if;
  end if;

  insert into public.orders (account_id, symbol, category, side, order_type, quantity,
    requested_price, execution_price, total_amount)
  values (p_account_id, p_symbol, p_category, p_side, p_order_type, p_quantity,
    p_requested_price, p_execution_price, v_total)
  returning * into v_order;

  return jsonb_build_object('account', to_jsonb(v_account),
    'holding', case when v_holding.id is null then null else to_jsonb(v_holding) end,
    'order', to_jsonb(v_order));
end;
$$;

revoke all on function public.place_spot_order(bigint, text, text, text, text, numeric, numeric, numeric)
  from public, anon, authenticated;
grant execute on function public.place_spot_order(bigint, text, text, text, text, numeric, numeric, numeric)
  to service_role;

comment on function public.place_spot_order is
  '계좌 잠금 후 잔액·보유종목·체결내역을 하나의 트랜잭션으로 변경한다.';
