create table if not exists public.finance_contracts (
  account_id bigint not null references public.accounts(id) on delete cascade,
  product_type text not null check (product_type in ('credit','margin','lending','collateral')),
  active boolean not null default false,
  limit_amount numeric(30,2) not null default 0 check (limit_amount >= 0),
  debt numeric(30,2) not null default 0 check (debt >= 0),
  locked_amount numeric(30,2) not null default 0 check (locked_amount >= 0),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  primary key (account_id, product_type)
);

create table if not exists public.short_positions (
  account_id bigint not null references public.accounts(id) on delete cascade,
  symbol text not null,
  quantity numeric(30,8) not null check (quantity > 0),
  avg_price numeric(30,8) not null check (avg_price > 0),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  primary key (account_id, symbol)
);

create table if not exists public.cash_ledger (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  event_type text not null,
  amount numeric(30,2) not null,
  balance_after numeric(30,2) not null,
  reference_type text, reference_id text,
  created_at timestamptz not null default now()
);
create index if not exists cash_ledger_account_created_idx on public.cash_ledger(account_id,created_at desc);

alter table public.finance_contracts enable row level security;
alter table public.short_positions enable row level security;
alter table public.cash_ledger enable row level security;

create or replace function public.execute_finance_contract(p_account_id bigint,p_product_type text,p_amount numeric,p_stock_value numeric)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_account public.accounts%rowtype; v_contract public.finance_contracts%rowtype; v_maximum numeric(30,2); v_locked numeric(30,2):=0; v_delta numeric(30,2);
begin
 if p_product_type not in ('credit','margin','lending','collateral') then raise exception using errcode='22023',message='지원하지 않는 금융상품입니다.'; end if;
 if p_amount is null or p_amount<100000 then raise exception using errcode='22023',message='실행금액은 10만원 이상이어야 합니다.'; end if;
 select * into v_account from public.accounts where id=p_account_id for update;
 if not found then raise exception using errcode='P0002',message='계좌를 찾을 수 없습니다.'; end if;
 select * into v_contract from public.finance_contracts where account_id=p_account_id and product_type=p_product_type for update;
 if v_contract.active then raise exception using errcode='P0001',message='이미 실행 중인 금융상품입니다.'; end if;
 v_maximum:=case p_product_type when 'credit' then floor(v_account.krw_balance*2) when 'margin' then floor(v_account.krw_balance*0.4) when 'collateral' then floor(greatest(p_stock_value,0)*0.7) else floor(v_account.krw_balance+greatest(p_stock_value,0)) end;
 if p_amount>v_maximum then raise exception using errcode='P0001',message='실행 가능 한도를 초과했습니다.'; end if;
 if p_product_type='lending' then
  v_locked:=ceil(p_amount*0.4); if v_locked>v_account.krw_balance then raise exception using errcode='P0001',message='대주 담보금보다 예수금이 부족합니다.'; end if; v_delta:=-v_locked;
 else v_delta:=p_amount; end if;
 update public.accounts set krw_balance=krw_balance+v_delta,updated_at=now() where id=p_account_id returning * into v_account;
 insert into public.finance_contracts(account_id,product_type,active,limit_amount,debt,locked_amount)
 values(p_account_id,p_product_type,true,p_amount,case when p_product_type='lending' then 0 else p_amount end,v_locked)
 on conflict(account_id,product_type) do update set active=true,limit_amount=excluded.limit_amount,debt=excluded.debt,locked_amount=excluded.locked_amount,updated_at=now()
 returning * into v_contract;
 insert into public.cash_ledger(account_id,event_type,amount,balance_after,reference_type,reference_id)
 values(p_account_id,'FINANCE_EXECUTE',v_delta,v_account.krw_balance,'finance_contract',p_product_type);
 return jsonb_build_object('account',to_jsonb(v_account),'contract',to_jsonb(v_contract),'maximum',v_maximum);
end; $$;

create or replace function public.settle_finance_contract(p_account_id bigint,p_product_type text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_account public.accounts%rowtype; v_contract public.finance_contracts%rowtype; v_delta numeric(30,2);
begin
 if p_product_type not in ('credit','margin','lending','collateral') then raise exception using errcode='22023',message='지원하지 않는 금융상품입니다.'; end if;
 select * into v_account from public.accounts where id=p_account_id for update;
 if not found then raise exception using errcode='P0002',message='계좌를 찾을 수 없습니다.'; end if;
 select * into v_contract from public.finance_contracts where account_id=p_account_id and product_type=p_product_type for update;
 if v_contract.account_id is null or not v_contract.active then raise exception using errcode='P0001',message='실행 중인 금융상품이 아닙니다.'; end if;
 if p_product_type='lending' then
  if exists(select 1 from public.short_positions where account_id=p_account_id) then raise exception using errcode='P0001',message='대주잔고를 먼저 상환해야 합니다.'; end if;
  v_delta:=v_contract.locked_amount;
 else
  if v_account.krw_balance<v_contract.debt then raise exception using errcode='P0001',message='상환에 필요한 현금이 부족합니다.'; end if; v_delta:=-v_contract.debt;
 end if;
 update public.accounts set krw_balance=krw_balance+v_delta,updated_at=now() where id=p_account_id returning * into v_account;
 update public.finance_contracts set active=false,limit_amount=0,debt=0,locked_amount=0,updated_at=now()
 where account_id=p_account_id and product_type=p_product_type returning * into v_contract;
 insert into public.cash_ledger(account_id,event_type,amount,balance_after,reference_type,reference_id)
 values(p_account_id,'FINANCE_SETTLE',v_delta,v_account.krw_balance,'finance_contract',p_product_type);
 return jsonb_build_object('account',to_jsonb(v_account),'contract',to_jsonb(v_contract));
end; $$;

revoke all on function public.execute_finance_contract(bigint,text,numeric,numeric) from public,anon,authenticated;
revoke all on function public.settle_finance_contract(bigint,text) from public,anon,authenticated;
grant execute on function public.execute_finance_contract(bigint,text,numeric,numeric) to service_role;
grant execute on function public.settle_finance_contract(bigint,text) to service_role;
