-- 삭제·수정할 수 없는 감사 원장. 기존 cash_ledger의 모든 새 기록을 자동 복제한다.
create table if not exists public.account_ledger (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  entry_group_id uuid not null default gen_random_uuid(),
  event_type text not null,
  currency text not null default 'KRW' check (currency in ('KRW', 'USD')),
  amount numeric(30,4) not null,
  balance_before numeric(30,4),
  balance_after numeric(30,4) not null,
  reference_type text,
  reference_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists account_ledger_account_created_idx on public.account_ledger(account_id, created_at desc, id desc);

alter table public.cash_ledger add column if not exists entry_group_id uuid;
alter table public.cash_ledger add column if not exists currency text not null default 'KRW';
alter table public.cash_ledger add column if not exists balance_before numeric(30,4);
alter table public.cash_ledger add column if not exists metadata jsonb not null default '{}'::jsonb;

-- 이전 현금 흐름도 한 번만 감사 원장으로 복원한다.
insert into public.account_ledger(account_id, entry_group_id, event_type, currency, amount, balance_before, balance_after, reference_type, reference_id, metadata, created_at)
select c.account_id, coalesce(c.entry_group_id, gen_random_uuid()), c.event_type, coalesce(c.currency,'KRW'), c.amount,
  coalesce(c.balance_before, c.balance_after-c.amount), c.balance_after, c.reference_type, c.reference_id,
  coalesce(c.metadata,'{}'::jsonb) || jsonb_build_object('cash_ledger_id',c.id), c.created_at
from public.cash_ledger c
where not exists(select 1 from public.account_ledger l where l.metadata->>'cash_ledger_id'=c.id::text);

create or replace function public.mirror_cash_ledger_to_account_ledger()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.account_ledger(account_id,entry_group_id,event_type,currency,amount,balance_before,balance_after,reference_type,reference_id,metadata,created_at)
  values(new.account_id,coalesce(new.entry_group_id,gen_random_uuid()),new.event_type,coalesce(new.currency,'KRW'),new.amount,
    coalesce(new.balance_before,new.balance_after-new.amount),new.balance_after,new.reference_type,new.reference_id,
    coalesce(new.metadata,'{}'::jsonb)||jsonb_build_object('cash_ledger_id',new.id),new.created_at);
  return new;
end;$$;
drop trigger if exists cash_ledger_mirror_to_account_ledger on public.cash_ledger;
create trigger cash_ledger_mirror_to_account_ledger after insert on public.cash_ledger
for each row execute function public.mirror_cash_ledger_to_account_ledger();

create or replace function public.prevent_account_ledger_mutation()
returns trigger language plpgsql as $$ begin raise exception using errcode='55000',message='계좌 원장은 수정하거나 삭제할 수 없습니다.'; end; $$;
drop trigger if exists account_ledger_immutable on public.account_ledger;
create trigger account_ledger_immutable before update or delete on public.account_ledger
for each row execute function public.prevent_account_ledger_mutation();

-- 주문 상태와 수량을 별도 관리하고, 모든 상태 전이를 append-only 이벤트로 기록한다.
alter table public.orders add column if not exists client_order_id uuid;
alter table public.orders add column if not exists filled_quantity numeric(30,8) not null default 0;
alter table public.orders add column if not exists remaining_quantity numeric(30,8) not null default 0;
alter table public.orders add column if not exists cancelled_quantity numeric(30,8) not null default 0;
alter table public.orders add column if not exists updated_at timestamptz not null default now();
update public.orders set filled_quantity=case when status='FILLED' then quantity else filled_quantity end,
  remaining_quantity=case when status='FILLED' then 0 else greatest(quantity-filled_quantity,0) end
where filled_quantity=0 and remaining_quantity=0;
create unique index if not exists orders_account_client_order_id_unique_idx on public.orders(account_id,client_order_id) where client_order_id is not null;

create or replace function public.normalize_order_quantities()
returns trigger language plpgsql as $$
begin
  if tg_op='INSERT' and new.filled_quantity=0 and new.remaining_quantity=0 then
    if new.status='FILLED' then new.filled_quantity:=new.quantity; new.remaining_quantity:=0;
    else new.remaining_quantity:=new.quantity; end if;
  end if;
  new.updated_at:=now();
  return new;
end;$$;
drop trigger if exists orders_normalize_quantities on public.orders;
create trigger orders_normalize_quantities before insert or update on public.orders
for each row execute function public.normalize_order_quantities();

create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  order_id uuid,
  event_type text not null check(event_type in ('ACCEPTED','OPEN','PARTIALLY_FILLED','FILLED','CANCELLED','REJECTED')),
  filled_quantity numeric(30,8) not null default 0,
  remaining_quantity numeric(30,8) not null default 0,
  execution_price numeric(30,8),
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists order_events_account_created_idx on public.order_events(account_id,created_at desc,id desc);
create index if not exists order_events_order_created_idx on public.order_events(order_id,created_at,id);

insert into public.order_events(account_id,order_id,event_type,filled_quantity,remaining_quantity,metadata,created_at)
select o.account_id,o.id,'ACCEPTED',0,o.quantity,jsonb_build_object('source','migration_backfill'),o.created_at
from public.orders o where not exists(select 1 from public.order_events e where e.order_id=o.id and e.event_type='ACCEPTED');
insert into public.order_events(account_id,order_id,event_type,filled_quantity,remaining_quantity,execution_price,metadata,created_at)
select o.account_id,o.id,'FILLED',o.quantity,0,o.execution_price,jsonb_build_object('source','migration_backfill'),o.created_at
from public.orders o where o.status='FILLED' and not exists(select 1 from public.order_events e where e.order_id=o.id and e.event_type='FILLED');

create or replace function public.record_order_event()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if tg_op='INSERT' then
    insert into public.order_events(account_id,order_id,event_type,filled_quantity,remaining_quantity,metadata,created_at)
    values(new.account_id,new.id,'ACCEPTED',0,new.quantity,jsonb_build_object('source','order_insert'),new.created_at);
    if new.status='FILLED' then
      insert into public.order_events(account_id,order_id,event_type,filled_quantity,remaining_quantity,execution_price,metadata,created_at)
      values(new.account_id,new.id,'FILLED',new.quantity,0,new.execution_price,jsonb_build_object('source','order_insert'),new.created_at);
    end if;
  elsif new.status is distinct from old.status or new.filled_quantity is distinct from old.filled_quantity or new.remaining_quantity is distinct from old.remaining_quantity then
    insert into public.order_events(account_id,order_id,event_type,filled_quantity,remaining_quantity,execution_price,metadata)
    values(new.account_id,new.id,new.status,new.filled_quantity,new.remaining_quantity,
      case when new.filled_quantity>old.filled_quantity then new.execution_price else null end,jsonb_build_object('source','order_update'));
  end if;
  return new;
end;$$;
drop trigger if exists orders_record_event on public.orders;
create trigger orders_record_event after insert or update of status,filled_quantity,remaining_quantity on public.orders
for each row execute function public.record_order_event();

create or replace function public.prevent_order_event_mutation()
returns trigger language plpgsql as $$ begin raise exception using errcode='55000',message='주문 이벤트는 수정하거나 삭제할 수 없습니다.'; end; $$;
drop trigger if exists order_events_immutable on public.order_events;
create trigger order_events_immutable before update or delete on public.order_events
for each row execute function public.prevent_order_event_mutation();

alter table public.account_ledger enable row level security;
alter table public.order_events enable row level security;
revoke all on table public.account_ledger,public.order_events from anon,authenticated;
grant select on table public.account_ledger,public.order_events to authenticated;
drop policy if exists account_ledger_select_own on public.account_ledger;
create policy account_ledger_select_own on public.account_ledger for select to authenticated using(
  auth.uid() is not null and exists(select 1 from public.accounts a where a.id=account_id and a.user_id=auth.uid())
);
drop policy if exists order_events_select_own on public.order_events;
create policy order_events_select_own on public.order_events for select to authenticated using(
  auth.uid() is not null and exists(select 1 from public.accounts a where a.id=account_id and a.user_id=auth.uid())
);
