-- 유지증거금, 마진콜, 강제청산 감사 기록을 위한 모의 위험관리 정책.
create table if not exists public.risk_policies(
  code text primary key,name text not null,warning_ratio numeric(12,6) not null,
  margin_call_ratio numeric(12,6) not null,liquidation_ratio numeric(12,6) not null,
  updated_at timestamptz not null default now()
);
insert into public.risk_policies values
  ('FUTURES','선물 유지증거금',0.85,0.75,0.50,now()),
  ('FINANCE','신용·담보 유지비율',1.50,1.40,1.20,now())
on conflict(code) do nothing;

create table if not exists public.risk_snapshots(
  id bigint generated by default as identity primary key,account_id bigint not null references public.accounts(id) on delete cascade,
  status text not null check(status in('SAFE','WARNING','MARGIN_CALL','LIQUIDATION')),
  equity numeric(30,2) not null,required_margin numeric(30,2) not null,margin_ratio numeric(18,8),
  deficit numeric(30,2) not null default 0,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now()
);
create index if not exists risk_snapshots_account_created_idx on public.risk_snapshots(account_id,created_at desc);
create table if not exists public.margin_calls(
  id uuid primary key default gen_random_uuid(),account_id bigint not null references public.accounts(id) on delete cascade,
  snapshot_id bigint references public.risk_snapshots(id),status text not null default 'OPEN' check(status in('OPEN','RESOLVED','LIQUIDATED')),
  required_amount numeric(30,2) not null default 0,due_at timestamptz not null,created_at timestamptz not null default now(),resolved_at timestamptz
);

create or replace function public.record_risk_snapshot(p_account_id bigint,p_status text,p_equity numeric,
  p_required_margin numeric,p_margin_ratio numeric,p_deficit numeric,p_details jsonb)
returns public.risk_snapshots language plpgsql security definer set search_path=public as $$
declare v_snapshot public.risk_snapshots%rowtype;
begin
  insert into public.risk_snapshots(account_id,status,equity,required_margin,margin_ratio,deficit,details)
  values(p_account_id,p_status,p_equity,p_required_margin,p_margin_ratio,greatest(coalesce(p_deficit,0),0),coalesce(p_details,'{}')) returning * into v_snapshot;
  if p_status in('MARGIN_CALL','LIQUIDATION') and not exists(select 1 from public.margin_calls where account_id=p_account_id and status='OPEN') then
    insert into public.margin_calls(account_id,snapshot_id,required_amount,due_at)
    values(p_account_id,v_snapshot.id,greatest(coalesce(p_deficit,0),0),now()+interval '1 day');
  elsif p_status in('SAFE','WARNING') then
    update public.margin_calls set status='RESOLVED',resolved_at=now() where account_id=p_account_id and status='OPEN';
  end if;
  return v_snapshot;
end; $$;

create or replace function public.force_liquidate_futures_position(p_account_id bigint,p_position_id uuid,p_current_price numeric)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_account public.accounts%rowtype;v_position public.futures_positions%rowtype;
  v_pnl numeric(30,2);v_payout numeric(30,2);v_delta numeric(30,2);v_deficit numeric(30,2);v_direction integer;
begin
  select * into v_account from public.accounts where id=p_account_id for update;
  select * into v_position from public.futures_positions where id=p_position_id and account_id=p_account_id for update;
  if not found then raise exception using errcode='P0002',message='선물 포지션을 찾을 수 없습니다.';end if;
  v_direction:=case when v_position.side='LONG' then 1 else -1 end;
  v_pnl:=round((p_current_price-v_position.entry_price)*v_position.multiplier*v_position.quantity*v_direction,2);
  v_payout:=v_position.margin+v_pnl;v_delta:=greatest(-v_account.krw_balance,v_payout);
  v_deficit:=greatest(0,-(v_account.krw_balance+v_payout));
  update public.accounts set krw_balance=krw_balance+v_delta,updated_at=now() where id=p_account_id returning * into v_account;
  delete from public.futures_positions where id=v_position.id;
  insert into public.cash_ledger(account_id,event_type,amount,balance_after,reference_type,reference_id,metadata)
  values(p_account_id,'FORCED_LIQUIDATION',v_delta,v_account.krw_balance,'futures_position',v_position.id::text,
    jsonb_build_object('pnl',v_pnl,'payout',v_payout,'deficit',v_deficit,'current_price',p_current_price));
  update public.margin_calls set status='LIQUIDATED',resolved_at=now() where account_id=p_account_id and status='OPEN';
  return jsonb_build_object('account',to_jsonb(v_account),'position',to_jsonb(v_position),'pnl',v_pnl,'payout',v_payout,'deficit',v_deficit);
end; $$;

alter table public.risk_snapshots enable row level security;alter table public.margin_calls enable row level security;alter table public.risk_policies enable row level security;
revoke all on table public.risk_snapshots,public.margin_calls,public.risk_policies from anon,authenticated;
grant select on table public.risk_snapshots,public.margin_calls,public.risk_policies to authenticated;
create policy risk_snapshots_select_own on public.risk_snapshots for select to authenticated using(exists(select 1 from public.accounts a where a.id=account_id and a.user_id=auth.uid()));
create policy margin_calls_select_own on public.margin_calls for select to authenticated using(exists(select 1 from public.accounts a where a.id=account_id and a.user_id=auth.uid()));
create policy risk_policies_read on public.risk_policies for select to authenticated using(true);
revoke all on function public.record_risk_snapshot(bigint,text,numeric,numeric,numeric,numeric,jsonb) from public,anon,authenticated;
revoke all on function public.force_liquidate_futures_position(bigint,uuid,numeric) from public,anon,authenticated;
grant execute on function public.record_risk_snapshot(bigint,text,numeric,numeric,numeric,numeric,jsonb) to service_role;
grant execute on function public.force_liquidate_futures_position(bigint,uuid,numeric) to service_role;
